#!/usr/bin/env bash

tmp1=$(acpi -b | awk '{print $4}' | tr -d ,)
tmp2=$(acpi -b | awk '{print $3}' | tr -d ,)

if [ $tmp2 == "Discharging" ]
then
	state="DIS"
else
	state="CHR"
fi
out="${tmp1}:${state}"

echo $out
echo $out

tmp3=$(echo $tmp1 | tr -d %)

if [ $state == "DIS" ]
then

	if [ $tmp3 -lt 25 ]
	then
		echo \#FF0000
		notify-send -u critical "Battery level critical" "Battery at ${tmp1}"
	else
		echo \#ffffff
	fi
else
	echo \#ffffff
fi
